### ISSUE TITLE
Could not find a version that satisfies the requirement torch==0.3.1

### ISSUE THREAD

**Issue by enriquea** [martinjzhang/adafdr#2]
Hi @martinjzhang,

Trying to get AdaFDR installed, I'm getting the following error:

```
Could not find a version that satisfies the requirement torch==0.3.1 (from versions: 0.1.2, 0.1.2.post1, 0.4.1, 0.4.1.post2, 1.0.0) 
No matching distribution found for torch==0.3.1
```

Any idea?

Thanks in advance!

**Comment by martinjzhang** [comment]
Hi @enriquea,

A quick question: which python version are you using? 

Best,
Martin

**Comment by enriquea** [comment]
Hi,

I just realised it works fine for Python 3.6.4. I was using before the version 3.7.1.

So I will close here.

Best,

Enrique
